version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./src:var/www/html
    ports:
      - "8080:80"
    networks:
      - webnet

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    columes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge