services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - storage:/var/www/html/storage # pour le volume de storage
    ports:
      - "8080:80"
    networks:
      - webnet

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_db 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb-data:/var/lib/mysql # pour le volume de mariadb
    ports:
      - "7000:3306"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  storage:
  mariadb-data: